name: pathlume
description: PATHLUME - Walk-to-Map Indoor AR Navigation System.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/demo/
