import { MapConfig } from './mapTypes';

export const DEFAULT_MAP_REGISTRY: Record<string, MapConfig> = {
    college_block_a: {
        mapId: 'college_block_a',
        name: 'College Block A',
        model: '/sample.glb',
        floor: 1,
        vpsMapId: 'college_block_a',
        anchors: {
            entrance_01: {
                id: 'entrance_01',
                name: 'Main Entrance',
                floor: 1,
                position: { x: 0, y: 0, z: 7.0 },
            },
            entrance_north: {
                id: 'entrance_north',
                name: 'North Gate Entrance',
                floor: 1,
                position: { x: 0, y: 0, z: -7.0 },
            },
        },
        destinations: [
            {
                id: 'room_101',
                name: 'Room 101',
                type: 'Room',
                floor: 1,
                position: { x: -1.8, y: 0, z: 6.0 },
                navigationNodeId: 'room_101',
            },
            {
                id: 'room_102',
                name: 'Room 102',
                type: 'Room',
                floor: 1,
                position: { x: -1.8, y: 0, z: -1.0 },
                navigationNodeId: 'room_102',
            },
            {
                id: 'laboratory',
                name: 'Laboratory',
                type: 'Lab',
                floor: 1,
                position: { x: 1.8, y: 0, z: 6.0 },
                navigationNodeId: 'room_103',
            },
            {
                id: 'library',
                name: 'Library',
                type: 'Library',
                floor: 1,
                position: { x: 1.8, y: 0, z: -1.0 },
                navigationNodeId: 'room_104',
            },
            {
                id: 'cafeteria',
                name: 'Cafeteria',
                type: 'Cafeteria',
                floor: 1,
                position: { x: 0, y: 0, z: -7.0 },
                navigationNodeId: 'room_105',
            },
            {
                id: 'auditorium',
                name: 'Auditorium',
                type: 'Auditorium',
                floor: 1,
                position: { x: 1.8, y: 0, z: -1.0 },
                navigationNodeId: 'room_104',
            },
            {
                id: 'reception',
                name: 'Reception',
                type: 'Reception',
                floor: 1,
                position: { x: 0, y: 0, z: 3.5 },
                navigationNodeId: 'lobby_center',
            },
        ],
        transformConfig: {
            translation: { x: 0, y: -1.9, z: 0 },
            rotation: { x: 0, y: 0, z: 0 },
            scale: 1.0,
        },
    },
    building_01: {
        mapId: 'building_01',
        name: 'Main Campus Building 1',
        model: '/sample1.glb',
        floor: 1,
        vpsMapId: 'building_01',
        anchors: {
            main_entrance: {
                id: 'main_entrance',
                name: 'Main Entrance',
                floor: 1,
                position: { x: 0, y: 0, z: 7.0 },
            },
        },
        destinations: [
            {
                id: 'room_101',
                name: 'Room 101 (Conference A)',
                type: 'Conference',
                floor: 1,
                position: { x: -1.8, y: 0, z: 6.0 },
                navigationNodeId: 'room_101',
            },
            {
                id: 'room_102',
                name: 'Room 102 (Lab)',
                type: 'Lab',
                floor: 1,
                position: { x: -1.8, y: 0, z: -1.0 },
                navigationNodeId: 'room_102',
            },
            {
                id: 'room_103',
                name: 'Room 103 (Office B)',
                type: 'Office',
                floor: 1,
                position: { x: 1.8, y: 0, z: 6.0 },
                navigationNodeId: 'room_103',
            },
            {
                id: 'room_104',
                name: 'Room 104 (Auditorium)',
                type: 'Auditorium',
                floor: 1,
                position: { x: 1.8, y: 0, z: -1.0 },
                navigationNodeId: 'room_104',
            },
            {
                id: 'room_105',
                name: 'Room 105 (Cafeteria)',
                type: 'Cafeteria',
                floor: 1,
                position: { x: 0, y: 0, z: -7.0 },
                navigationNodeId: 'room_105',
            },
        ],
        transformConfig: {
            translation: { x: 0, y: -1.9, z: 0 },
            rotation: { x: 0, y: 0, z: 0 },
            scale: 1.0,
        },
    },
};
